// SPDX-FileCopyrightText: 2025 Steve <marlumpy@gmail.com>
// SPDX-FileCopyrightText: 2025 marc-pelletier <113944176+marc-pelletier@users.noreply.github.com>
// SPDX-FileCopyrightText: 2026 Triad Sector
//
// SPDX-License-Identifier: AGPL-3.0-or-later

using System.Linq;
using System.Numerics;
using Content.Client.RCD;
using Content.Client.UserInterface.Controls;
using Content.Shared.RCD;
using Content.Shared.RPD;
using Robust.Client.AutoGenerated;
using Robust.Client.Graphics;
using Robust.Client.UserInterface;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Prototypes;

namespace Content.Client.RPD;

/// <summary>
/// Wraps the standard RCDMenu radial with a color-picker strip below it. Operator can build pipes in a chosen
/// palette color via <c>PipeColorVisualsComponent</c>. Swatches render in two centered rows: general pipe-loop
/// labels on top, alphabetized named gases below.
/// </summary>
[GenerateTypedNameReferences]
public sealed partial class RPDMenu : RadialMenu
{
    [Dependency] private readonly ILocalizationManager _locManager = default!;

    private readonly RCDMenu _rcdMenu;
    private string? _selectedColor;

    public event Action<string>? ColorSelected;

    public event Action<ProtoId<RCDPrototype>>? SendRCDSystemMessageAction
    {
        add => _rcdMenu.SendRCDSystemMessageAction += value;
        remove => _rcdMenu.SendRCDSystemMessageAction -= value;
    }

    public RPDMenu()
    {
        IoCManager.InjectDependencies(this);
        RobustXamlLoader.Load(this);
        _rcdMenu = new RCDMenu();
        var rcdHolder = FindControl<Control>("RCDMenuHolder");
        rcdHolder.AddChild(_rcdMenu);
        _rcdMenu.OnClose += Close;
    }

    public void SetEntity(EntityUid uid)
    {
        _rcdMenu.SetEntity(uid);
    }

    public void Populate(IReadOnlyDictionary<string, Color?> palette, string selectedColor = "default")
    {
        _selectedColor = palette.ContainsKey(selectedColor) ? selectedColor : "default";

        var generalRow = FindControl<BoxContainer>("GeneralColorList");
        var gasRow = FindControl<BoxContainer>("GasColorList");
        if (generalRow == null || gasRow == null)
            return;

        PopulateRow(generalRow, RPDPalette.GeneralKeys, palette);
        PopulateRow(gasRow, RPDPalette.GasKeys, palette);

        UpdateAllButtonBorders();
    }

    private void PopulateRow(BoxContainer row, IReadOnlyList<string> keys, IReadOnlyDictionary<string, Color?> palette)
    {
        foreach (var child in row.Children)
            child.Dispose();
        row.RemoveAllChildren();

        foreach (var key in keys)
        {
            if (!palette.TryGetValue(key, out var color))
                continue;

            row.AddChild(BuildSwatchButton(key, color));
        }
    }

    private Button BuildSwatchButton(string key, Color? color)
    {
        var button = new Button
        {
            Name = $"ColorBox_{key}",
            Visible = true,
            MinSize = new Vector2(30, 30),
            MaxSize = new Vector2(30, 30),
            Margin = new Thickness(6),
            StyleClasses = { "OpenBoth" },
            ToolTip = _locManager.GetString(key),
        };

        var colorPanel = new PanelContainer
        {
            MinSize = new Vector2(30, 30),
            MaxSize = new Vector2(30, 30),
            PanelOverride = color != null
                ? new StyleBoxFlat { BackgroundColor = color.Value }
                : new StyleBoxFlat { BackgroundColor = Color.Transparent },
        };

        UpdateButtonBorder(colorPanel, key);

        button.OnMouseEntered += _ =>
        {
            if (colorPanel.PanelOverride is not StyleBoxFlat hover)
                return;
            hover.BorderColor = Color.LightBlue;
            hover.BorderThickness = new Thickness(3);
        };

        button.OnMouseExited += _ => UpdateButtonBorder(colorPanel, key);

        button.OnPressed += _ =>
        {
            if (_selectedColor == key)
                return;
            _selectedColor = key;
            UpdateAllButtonBorders();
            ColorSelected?.Invoke(_selectedColor);
        };

        button.AddChild(colorPanel);
        return button;
    }

    private void UpdateButtonBorder(PanelContainer panel, string colorKey)
    {
        if (panel.PanelOverride is not StyleBoxFlat styleBox)
            return;

        if (_selectedColor == colorKey)
        {
            styleBox.BorderColor = Color.Gold;
            styleBox.BorderThickness = new Thickness(3);
        }
        else
        {
            styleBox.BorderColor = Color.Transparent;
            styleBox.BorderThickness = new Thickness(3);
        }
    }

    private void UpdateAllButtonBorders()
    {
        foreach (var rowName in new[] { "GeneralColorList", "GasColorList" })
        {
            var row = FindControl<BoxContainer>(rowName);
            if (row == null)
                continue;

            foreach (var child in row.Children)
            {
                if (child is not Button button || button.Name == null)
                    continue;

                var colorKey = button.Name.StartsWith("ColorBox_")
                    ? button.Name["ColorBox_".Length..]
                    : null;
                if (colorKey == null)
                    continue;

                var panel = button.Children.OfType<PanelContainer>().FirstOrDefault();
                if (panel != null)
                    UpdateButtonBorder(panel, colorKey);
            }
        }
    }
}
