using System.Text;
using Content.Shared._DV.Traits;
using Content.Shared._DV.Traits.Conditions;
using Content.Shared._Mono.Traits.Conditions; // Mono - Company condition
using Content.Shared._Triad.Traits.Conditions; // Triad - free accent slot gate
using Content.Shared.Humanoid.Prototypes;
using Content.Shared.Roles;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.CustomControls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Prototypes;
using Robust.Shared.Utility;

namespace Content.Client._DV.Traits.UI;

[GenerateTypedNameReferences]
public sealed partial class TraitEntry : PanelContainer
{
    [Dependency] private readonly IPrototypeManager _prototype = default!;
    [Dependency] private readonly ILocalizationManager _loc = default!;

    public event Action<bool>? OnToggled;

    public bool IsSelected { get; private set; }
    public readonly int TraitCost;

    /// <summary>
    /// Whether the trait passes its conditions (species / job / mutex). False renders red and blocks selection.
    /// </summary>
    public bool MeetsConditions { get; private set; } = true;

    /// <summary>
    /// Triad: whether the player still has the budget (category/global trait slots and points) to add this trait.
    /// Pushed from the parent tab. An unselected, unaffordable entry renders grey and is unclickable; a selected
    /// one stays clickable so you can deselect to free budget. Does not gate already-selected entries.
    /// </summary>
    public bool Affordable { get; private set; } = true;

    // Triad: resolved text explaining WHY this entry is unaffordable (which budget was hit), shown on hover. Null when affordable.
    private string? _unaffordableReason;

    private readonly TraitPrototype _trait;
    private bool _isUpdating;

    public TraitEntry(TraitPrototype trait)
    {
        RobustXamlLoader.Load(this);
        IoCManager.InjectDependencies(this);

        _trait = trait;
        TraitCost = trait.Cost;

        // Tooltips are supplied on the panel; it needs to receive mouse-over to show them.
        MouseFilter = MouseFilterMode.Pass;

        TraitNameLabel.Text = Loc.GetString(trait.Name);

        // Triad: parse the description as markup so [italic] flavor renders. Fall back to plain text if a
        // description has malformed markup, so one bad string can't blank or crash the entry.
        var desc = Loc.GetString(trait.Description);
        try
        {
            TraitDescriptionLabel.SetMessage(FormattedMessage.FromMarkupOrThrow(desc));
        }
        catch (Exception)
        {
            TraitDescriptionLabel.SetMessage(desc);
        }

        // Format cost display: positive trait cost spends points, negative trait cost grants points.
        var costText = trait.Cost switch
        {
            > 0 => $"-{trait.Cost}",
            < 0 => $"+{System.Math.Abs(trait.Cost)}",
            _ => "0"
        };
        var costColor = trait.Cost > 0 ? "#6bff6b" : trait.Cost < 0 ? "#ff6b6b" : "#888888";
        TraitCostLabel.Text = costText;
        TraitCostLabel.ModulateSelfOverride = Color.FromHex(costColor);

        // Triad: the whole row is the hit target now (users kept missing the small checkbox). A transparent
        // full-bleed button (ClickArea) catches the click; the panel itself carries the green/red/grey stylebox.
        ClickArea.OnPressed += OnEntryPressed;

        // Build the hover tooltip (condition or budget reason).
        UpdateTooltip();
        UpdateVisualState();

        // Triad: pin the description wrap width to the entry's real arranged width (see UpdateDescriptionWrap).
        OnResized += UpdateDescriptionWrap;
    }

    private void UpdateDescriptionWrap()
    {
        // This editor measures entries wider than they finally arrange (the lobby sprite panel claims space at
        // arrange time), so RichTextLabel caches a too-wide wrap and clips at the column edge. Pin the label's max
        // width to its PARENT column's arranged width, which the layout pass has already sized correctly around the
        // lock and cost. Reading the real arranged width (not entry-width-minus-guesses) self-corrects when the
        // cost is hidden or margins change, instead of over-reserving and wrapping early.
        if (TraitDescriptionLabel.Parent is not { } column)
            return;
        var available = column.Width;
        if (available > 0f && System.Math.Abs(TraitDescriptionLabel.MaxWidth - available) > 0.5f)
            TraitDescriptionLabel.MaxWidth = available;
    }

    // Triad: the tooltip explains why an entry can't be taken. Rule-blocked (red) entries list their failed
    // conditions; budget-blocked (grey) entries show which limit was hit. It is attached to ClickArea, not the
    // panel, because the full-bleed ClickArea button sits on top and is what actually receives the mouse-over.
    private void UpdateTooltip()
    {
        string? text = null;

        if (!MeetsConditions)
        {
            var conditions = new StringBuilder();
            foreach (var condition in _trait.Conditions)
                conditions.Append(condition.GetTooltip(_prototype, _loc, 0));

            if (conditions.Length > 0)
                text = Loc.GetString("trait-conditions-tooltip", ("conditions", conditions.ToString())).ToString().Trim();
        }
        else if (!Affordable && _unaffordableReason != null)
        {
            text = _unaffordableReason;
        }

        if (text != null)
        {
            var markupTooltip = CreateMarkupTooltip(text);
            ClickArea.TooltipSupplier = _ => markupTooltip;
        }
        else
        {
            ClickArea.TooltipSupplier = null;
        }
    }

    /// <summary>
    /// Creates a tooltip control that properly parses markup.
    /// </summary>
    private static Tooltip CreateMarkupTooltip(string markupText)
    {
        var tooltip = new Tooltip();

        // Parse the markup into a FormattedMessage
        tooltip.SetMessage(FormattedMessage.FromMarkupOrThrow(markupText));

        return tooltip;
    }

    /// <summary>
    /// Updates whether conditions are met based on current job/species.
    /// </summary>
    public void UpdateConditionsMet(ProtoId<JobPrototype>? jobId, ProtoId<SpeciesPrototype>? speciesId, IReadOnlySet<ProtoId<AntagPrototype>>? antagPreferences, IReadOnlySet<ProtoId<TraitPrototype>>? traits, string? companyName) // Mono - Company condition
    {
        MeetsConditions = true;

        foreach (var condition in _trait.Conditions)
        {
            var result = condition switch
            {
                IsSpeciesCondition speciesCond => CheckSpeciesCondition(speciesCond, speciesId),
                HasJobCondition jobCond => CheckJobCondition(jobCond, jobId),
                InDepartmentCondition deptCond => CheckDepartmentCondition(deptCond, jobId),
                HasCompCondition compCond => !compCond.Invert, // can't check in lobby but screws with the inversion logic
                IsAntagEligibleCondition antagEligibleCond => CheckAntagEligibleCondition(antagEligibleCond, antagPreferences),
                HasTraitCondition hasTrait => CheckHasTraitCondition(hasTrait, traits),
                HasFreeAccentSlotCondition => CheckFreeAccentSlot(speciesId, traits), // Triad - free accent slot gate
                InCompanyCondition inCompanyCond => CheckInCompanyCondition(inCompanyCond, companyName), // Mono - Company condition
                AnyOfCondition anyOfCond => CheckAnyOfCondition(anyOfCond, jobId, speciesId, antagPreferences, traits, companyName),
                AllOfCondition allOfCond => CheckAllOfCondition(allOfCond, jobId, speciesId, antagPreferences, traits, companyName),
                _ => true,
            };

            // Apply inversion
            result ^= condition.Invert;

            if (!result)
            {
                MeetsConditions = false;
            }
        }

        // Conditions no longer met: force-deselect (e.g. a mutex partner was just picked, or species changed).
        if (!MeetsConditions && IsSelected)
        {
            SetSelected(false);
            OnToggled?.Invoke(false);
        }

        UpdateVisualState();
    }

    /// <summary>
    /// Triad: set by the parent tab after recomputing budget. Drives the grey "can't afford" state.
    /// </summary>
    public void SetAffordable(bool affordable, string? reason = null)
    {
        Affordable = affordable;
        _unaffordableReason = reason;
        UpdateVisualState();
    }

    /// <summary>
    /// Triad: hide the point-cost label in categories with no point budget, where the cost is meaningless noise.
    /// </summary>
    public void SetCostVisible(bool visible)
    {
        TraitCostLabel.Visible = visible;
    }

    private bool CheckSpeciesCondition(IsSpeciesCondition condition, ProtoId<SpeciesPrototype>? speciesId)
    {
        if (!_prototype.TryIndex(speciesId, out var species))
            return false;

        return species == condition.Species;
    }

    private bool CheckJobCondition(HasJobCondition condition, ProtoId<JobPrototype>? jobId)
    {
        if (!_prototype.TryIndex(jobId, out var job))
            return false;

        return job == condition.Job;
    }

    private bool CheckDepartmentCondition(InDepartmentCondition condition, ProtoId<JobPrototype>? jobId)
    {
        if (!_prototype.TryIndex(jobId, out var job))
            return false;

        if (!_prototype.TryIndex(condition.Department, out var department))
            return false;

        return department.Roles.Contains(job);
    }

    private bool CheckAntagEligibleCondition(IsAntagEligibleCondition condition, IReadOnlySet<ProtoId<AntagPrototype>>? antagPreferences)
    {
        if (antagPreferences is null)
            return false;

        return antagPreferences.Contains(condition.Antag);
    }

    private bool CheckHasTraitCondition(HasTraitCondition condition, IReadOnlySet<ProtoId<TraitPrototype>>? traits)
    {
        if (traits is null)
            return false;

        return traits.Contains(condition.Trait);
    }

    // Triad: lobby mirror of HasFreeAccentSlotCondition. The editor can't read entity components, but it has the
    // selected species + trait set, which is all this gate needs. Shares the species list / unlock-trait id with
    // the shared condition so client and server evaluators can't drift.
    private bool CheckFreeAccentSlot(ProtoId<SpeciesPrototype>? speciesId, IReadOnlySet<ProtoId<TraitPrototype>>? traits)
    {
        if (speciesId is not { } species || Array.IndexOf(HasFreeAccentSlotCondition.HeavyNativeAccentSpecies, species) < 0)
            return true;

        return traits is not null && traits.Contains(HasFreeAccentSlotCondition.AccentlessTrait);
    }

    // Begin Mono - Company condition
    private bool CheckInCompanyCondition(InCompanyCondition condition, string? companyName) // Mono - Company condition
    {
        return string.Equals(condition.CompanyName, companyName);
    }
    // End Mono

    private bool CheckAnyOfCondition(AnyOfCondition condition, ProtoId<JobPrototype>? jobId, ProtoId<SpeciesPrototype>? speciesId, IReadOnlySet<ProtoId<AntagPrototype>>? antagPreferences, IReadOnlySet<ProtoId<TraitPrototype>>? traits, string? companyName) // Mono - Company condition
    {
        if (condition.Conditions.Count == 0)
            return false;

        // Return true if ANY child condition evaluates to true
        foreach (var childCondition in condition.Conditions)
        {
            var result = childCondition switch
            {
                IsSpeciesCondition speciesCond => CheckSpeciesCondition(speciesCond, speciesId),
                HasJobCondition jobCond => CheckJobCondition(jobCond, jobId),
                InDepartmentCondition deptCond => CheckDepartmentCondition(deptCond, jobId),
                HasCompCondition compCond => !compCond.Invert, // can't check in lobby
                IsAntagEligibleCondition antagEligibleCond => CheckAntagEligibleCondition(antagEligibleCond, antagPreferences),
                HasTraitCondition hasTrait => CheckHasTraitCondition(hasTrait, traits),
                HasFreeAccentSlotCondition => CheckFreeAccentSlot(speciesId, traits), // Triad - free accent slot gate
                InCompanyCondition inCompanyCond => CheckInCompanyCondition(inCompanyCond, companyName), // Mono - Company condition
                AnyOfCondition nestedAnyOf => CheckAnyOfCondition(nestedAnyOf, jobId, speciesId, antagPreferences, traits, companyName), // Recursive!
                AllOfCondition nestedAllOf => CheckAllOfCondition(nestedAllOf, jobId, speciesId, antagPreferences, traits, companyName),
                _ => true,
            };

            // Apply child's inversion
            result ^= childCondition.Invert;

            // If any child passes, the AnyOf passes
            if (result)
                return true;
        }

        // None of the children passed
        return false;
    }

    // Triad: client mirror of AllOfCondition — passes only if every child passes (logical AND), recursing into
    // nested AnyOf/AllOf. HasComp children can't be read in the lobby (same limit as elsewhere), so they pass.
    private bool CheckAllOfCondition(AllOfCondition condition, ProtoId<JobPrototype>? jobId, ProtoId<SpeciesPrototype>? speciesId, IReadOnlySet<ProtoId<AntagPrototype>>? antagPreferences, IReadOnlySet<ProtoId<TraitPrototype>>? traits, string? companyName)
    {
        if (condition.Conditions.Count == 0)
            return false;

        foreach (var childCondition in condition.Conditions)
        {
            var result = childCondition switch
            {
                IsSpeciesCondition speciesCond => CheckSpeciesCondition(speciesCond, speciesId),
                HasJobCondition jobCond => CheckJobCondition(jobCond, jobId),
                InDepartmentCondition deptCond => CheckDepartmentCondition(deptCond, jobId),
                HasCompCondition compCond => !compCond.Invert, // can't check in lobby
                IsAntagEligibleCondition antagEligibleCond => CheckAntagEligibleCondition(antagEligibleCond, antagPreferences),
                HasTraitCondition hasTrait => CheckHasTraitCondition(hasTrait, traits),
                HasFreeAccentSlotCondition => CheckFreeAccentSlot(speciesId, traits), // Triad - free accent slot gate
                InCompanyCondition inCompanyCond => CheckInCompanyCondition(inCompanyCond, companyName),
                AnyOfCondition nestedAnyOf => CheckAnyOfCondition(nestedAnyOf, jobId, speciesId, antagPreferences, traits, companyName),
                AllOfCondition nestedAllOf => CheckAllOfCondition(nestedAllOf, jobId, speciesId, antagPreferences, traits, companyName),
                _ => true,
            };

            result ^= childCondition.Invert;

            // If any child fails, the AllOf fails.
            if (!result)
                return false;
        }

        // Every child passed.
        return true;
    }

    private void OnEntryPressed(BaseButton.ButtonEventArgs args)
    {
        if (_isUpdating)
            return;

        // Rule-blocked entries (red) never toggle. Unaffordable unselected entries (grey) never toggle.
        // A selected entry always toggles off, so the player can free budget even when at the cap.
        if (!MeetsConditions)
            return;
        if (!IsSelected && !Affordable)
            return;

        SetSelected(!IsSelected);
        OnToggled?.Invoke(IsSelected);
    }

    public void SetSelected(bool selected)
    {
        _isUpdating = true;
        IsSelected = selected && MeetsConditions;
        UpdateVisualState();
        _isUpdating = false;
    }

    /// <summary>
    /// Triad: single source of truth for the entry's look. Four states, in priority order:
    /// rule-blocked (red, lock) &gt; selected (green) &gt; unaffordable (grey, lock) &gt; available (normal).
    /// </summary>
    private void UpdateVisualState()
    {
        RemoveStyleClass("TraitsEntrySelected");
        RemoveStyleClass("TraitsEntryRuleBlocked");
        RemoveStyleClass("TraitsEntryDisabled");
        LockIcon.Visible = false;

        if (!MeetsConditions)
        {
            // Blocked by a rule the player could only change via species/job/other selections.
            // ClickArea disabled so the row gives no press feedback, not just a no-op click.
            LockIcon.Visible = true;
            AddStyleClass("TraitsEntryRuleBlocked");
            ClickArea.Disabled = true;
        }
        else if (IsSelected)
        {
            // Always clickable so it can be deselected, even when the category/points are at the cap.
            AddStyleClass("TraitsEntrySelected");
            ClickArea.Disabled = false;
        }
        else if (!Affordable)
        {
            // No budget left; greyed and unclickable, with a lock icon so the affordance matches rule-blocked
            // entries. The hover tooltip explains which budget was hit.
            LockIcon.Visible = true;
            AddStyleClass("TraitsEntryDisabled");
            ClickArea.Disabled = true;
        }
        else
        {
            ClickArea.Disabled = false;
        }

        UpdateTooltip();
    }
}
